version : "3"
services :
  car-rental-system-API-1:
    image: car-rental-system-1
    #restart : always
    build: .
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST : car-db
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : admin
      
  car-rental-db-1: 
    container_name : car-db  
    image: postgres:10.20
    volumes :
     - ./DB_Records:/var/lib/postgresql/data
    ports: 
    - 5433:5432
    environment:
      POSTGRES_DB : carRentalSystem_Sprint1
      POSTGRES_PASSWORD : admin
      